#!/usr/bin/env python3
"""Apply the OKF evaluation's verified corrections to the endpoint tables.

On 2026-08-14, nine evaluator agents executed every documented call in the
OKF bundle against the live APIs (78 archive pages + 6 access guides,
~160 calls). Roughly 60% of documented calls were broken — decommissioned
APIs, moved hosts, fabricated example identifiers, template placeholders
shipped as examples. Each verified correction was recorded, with evidence,
in two seed CSVs; this script is the single writer that applies them:

  data/seed/okf_endpoint_fixes.csv   → api_endpoints
      columns: endpoint_id, archive_id, purpose, field, new_value,
               verdict, evidence
      field is one of path_or_url / example_call / method /
      response_format, or the sentinel DELETE-ROW (the endpoint has no
      working replacement — e.g. griddap rows on ERDDAPs that host zero
      griddap datasets — and keeping it would be a false claim).

  data/seed/okf_archive_fixes.csv    → data_archives
      columns: archive_id, field, new_value, verdict, evidence
      field is one of base_url / api_url / api_doc_url.

  data/seed/okf_product_fixes.csv    → data_products
      columns: product_id, field, new_value, verdict, evidence
      field is url (the only product column the evaluation touched).

Corrections live in the SOURCE tables, never in docs/okf/*.md — those
pages are generated by build_okf_bundle.py from public/parquet and any
hand edit is silently reverted on the next build. The canonical sequence
after this script is therefore:

    python scripts/apply_okf_fixes.py
    python scripts/qa.py
    python scripts/export_parquet.py
    python scripts/build_okf_bundle.py

Idempotent: an UPDATE to the current value changes nothing, and a
DELETE-ROW for an already-deleted endpoint reports 0. The CSVs are
append-only history — a fix that is later superseded gets a new row, and
rows apply in file order so the newest wins.

Usage::

    python scripts/apply_okf_fixes.py --dry-run
    python scripts/apply_okf_fixes.py
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB = ROOT / "db" / "lto.duckdb"
ENDPOINT_CSV = ROOT / "data" / "seed" / "okf_endpoint_fixes.csv"
ARCHIVE_CSV = ROOT / "data" / "seed" / "okf_archive_fixes.csv"

ENDPOINT_FIELDS = {"path_or_url", "example_call", "method", "response_format"}
ARCHIVE_FIELDS = {"base_url", "api_url", "api_doc_url"}
PRODUCT_CSV = ROOT / "data" / "seed" / "okf_product_fixes.csv"
PRODUCT_FIELDS = {"url"}


def apply_product_fixes(conn, dry: bool) -> tuple[int, list[str]]:
    updated = 0
    problems: list[str] = []
    if not PRODUCT_CSV.exists():
        return 0, []          # optional file — no product fixes recorded yet
    for i, row in enumerate(csv.DictReader(PRODUCT_CSV.open(encoding="utf-8")), 2):
        pid, field = row["product_id"], row["field"]
        if field not in PRODUCT_FIELDS:
            problems.append(f"line {i}: unknown field {field!r} for {pid}")
            continue
        exists = conn.execute(
            "SELECT count(*) FROM data_products WHERE product_id = ?", [pid]
        ).fetchone()[0]
        if not exists:
            problems.append(f"line {i}: unknown product_id {pid!r}")
            continue
        if not dry:
            conn.execute(
                f"UPDATE data_products SET {field} = ? WHERE product_id = ?",
                [row["new_value"], pid])
        updated += 1
    return updated, problems


def apply_endpoint_fixes(conn, dry: bool) -> tuple[int, int, list[str]]:
    updated = deleted = 0
    problems: list[str] = []
    if not ENDPOINT_CSV.exists():
        return 0, 0, [f"missing {ENDPOINT_CSV}"]
    for i, row in enumerate(csv.DictReader(ENDPOINT_CSV.open(encoding="utf-8")), 2):
        eid, field = row["endpoint_id"], row["field"]
        exists = conn.execute(
            "SELECT count(*) FROM api_endpoints WHERE endpoint_id = ?", [eid]
        ).fetchone()[0]
        if field == "DELETE-ROW":
            if exists and not dry:
                conn.execute("DELETE FROM api_endpoints WHERE endpoint_id = ?", [eid])
            deleted += exists
            continue
        if field not in ENDPOINT_FIELDS:
            problems.append(f"line {i}: unknown field {field!r} for {eid}")
            continue
        if not exists:
            # Deleted by an earlier DELETE-ROW in this same log — a
            # correction recorded before the delete verdict landed. Fine.
            continue
        if not dry:
            conn.execute(
                f"UPDATE api_endpoints SET {field} = ? WHERE endpoint_id = ?",
                [row["new_value"], eid])
        updated += 1
    return updated, deleted, problems


def apply_archive_fixes(conn, dry: bool) -> tuple[int, list[str]]:
    updated = 0
    problems: list[str] = []
    if not ARCHIVE_CSV.exists():
        return 0, [f"missing {ARCHIVE_CSV}"]
    for i, row in enumerate(csv.DictReader(ARCHIVE_CSV.open(encoding="utf-8")), 2):
        aid, field = row["archive_id"], row["field"]
        if field not in ARCHIVE_FIELDS:
            problems.append(f"line {i}: unknown field {field!r} for {aid}")
            continue
        exists = conn.execute(
            "SELECT count(*) FROM data_archives WHERE archive_id = ?", [aid]
        ).fetchone()[0]
        if not exists:
            problems.append(f"line {i}: unknown archive_id {aid!r}")
            continue
        if not dry:
            conn.execute(
                f"UPDATE data_archives SET {field} = ? WHERE archive_id = ?",
                [row["new_value"], aid])
        updated += 1
    return updated, problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", type=Path, default=DEFAULT_DB)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    conn = duckdb.connect(str(args.db))
    ep_updated, ep_deleted, ep_problems = apply_endpoint_fixes(conn, args.dry_run)
    ar_updated, ar_problems = apply_archive_fixes(conn, args.dry_run)
    pr_updated, pr_problems = apply_product_fixes(conn, args.dry_run)
    conn.close()

    tag = " (dry run — nothing written)" if args.dry_run else ""
    print(f"[fixes] api_endpoints: {ep_updated} field update(s), "
          f"{ep_deleted} row(s) deleted{tag}")
    print(f"[fixes] data_archives: {ar_updated} field update(s){tag}")
    print(f"[fixes] data_products: {pr_updated} field update(s){tag}")
    for p in ep_problems + ar_problems + pr_problems:
        print(f"[fixes] PROBLEM: {p}", file=sys.stderr)
    if ep_problems or ar_problems or pr_problems:
        return 1
    print("[fixes] next: qa.py → export_parquet.py → build_okf_bundle.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
