#!/usr/bin/env python3
"""Cross-validate the new coastal-terrestrial overlays against what's
already in the cod-kmap repo (legacy nps-coastal overlay, NERR/NEP/NMS
overlays, facilities table) and emit a gap report.

For each polygon in our new overlays we report whether the unit:
  * matches an existing facility row by exact-name or fuzzy-name,
  * matches a row in another overlay by name,
  * appears truly new — i.e. the cod-kmap dataset has no record of it.

Output: a Markdown table per layer plus per-state summaries, written to
``data/raw/R11_coastal_ecosystems/gap_report.md``. The report drives the
follow-on "Add overlays + facilities to map and database" task — every
truly-new unit becomes a candidate facility row.
"""
from __future__ import annotations

import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

import duckdb
from rapidfuzz import fuzz

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "data" / "raw" / "R11_coastal_ecosystems" / "gap_report.md"
DB = ROOT / "db" / "cod_kmap.duckdb"

NEW_LAYERS = [
    ("coastal-fws-units", "USFWS Refuges & Approved Boundaries"),
    ("coastal-nps-units", "NPS Coastal Units (LRD)"),
    ("coastal-usfs-special", "USFS RNAs / Experimental Forests"),
    ("coastal-wilderness", "National Wilderness Preservation System"),
]

LEGACY_LAYERS = [
    "nps-coastal", "nerr-reserves", "nep-programs",
    "marine-sanctuaries", "marine-monuments",
]


def load_layer(name: str) -> list[dict]:
    p = ROOT / "public" / "overlays" / f"{name}.geojson"
    with open(p) as f:
        d = json.load(f)
    return d.get("features") or []


def name_norm(s: str) -> str:
    return (s or "").strip().lower().replace("national wildlife refuge", "nwr") \
        .replace("national monument", "nm") \
        .replace("national park", "np") \
        .replace("national seashore", "nashore") \
        .replace("national lakeshore", "nlshore") \
        .replace("national preserve", "npreserve") \
        .replace("national recreation area", "nra")


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # Index every legacy overlay's names
    legacy_names: dict[str, set[str]] = {}
    for ln in LEGACY_LAYERS:
        feats = load_layer(ln)
        legacy_names[ln] = {name_norm(f["properties"].get("name", "")) for f in feats}

    # Index facilities table
    if DB.exists():
        with duckdb.connect(str(DB), read_only=True) as conn:
            facs = conn.execute(
                "SELECT facility_id, canonical_name, acronym FROM facilities"
            ).fetchall()
    else:
        facs = []
    fac_index = {name_norm(name): (fid, name, acr) for fid, name, acr in facs}
    fac_acr_index = {(acr or "").lower(): (fid, name, acr) for fid, name, acr in facs if acr}

    lines = ["# Coastal-terrestrial overlay gap report",
             "",
             f"Generated by `scripts/coastal_research/crossvalidate.py`. "
             f"Cross-validates the four new authoritative coastal overlays "
             f"against the {len(facs)} facilities currently in the DB and the "
             f"{len(LEGACY_LAYERS)} pre-existing region overlays.",
             "",
             "Per-layer breakdown follows. Status legend:",
             "",
             "* `match-facility` — name resolves to an existing facility row (no new ingest needed).",
             "* `match-legacy-overlay/<id>` — name resolves to an existing overlay polygon.",
             "* `fuzzy-facility/<score>` — close-but-not-exact facility match (manual review).",
             "* `new` — truly new unit; candidate for ingestion.",
             ""]

    summary = []
    for layer_id, label in NEW_LAYERS:
        feats = load_layer(layer_id)
        rows = []
        states = Counter()
        statuses = Counter()
        for f in feats:
            p = f["properties"]
            nm = p.get("name", "")
            nm_n = name_norm(nm)
            st = p.get("state", "")
            states[st] += 1
            status = "new"
            if nm_n in fac_index:
                fid, fnm, fac = fac_index[nm_n]
                status = f"match-facility:{fac or fnm}"
            else:
                for ln in LEGACY_LAYERS:
                    if nm_n in legacy_names[ln]:
                        status = f"match-legacy-overlay/{ln}"
                        break
                if status == "new":
                    # fuzzy facility
                    best = (0, "")
                    for fac_n, (fid, fnm, acr) in fac_index.items():
                        s = fuzz.token_set_ratio(nm_n, fac_n)
                        if s > best[0]:
                            best = (s, fnm)
                    if best[0] >= 88:
                        status = f"fuzzy-facility/{best[0]}:{best[1]}"
            statuses[status.split(':', 1)[0]] += 1
            rows.append((nm, st, p.get("kind", ""), p.get("area_acres", ""), status))
        summary.append((layer_id, label, len(feats), dict(statuses), dict(states)))

        lines.append(f"## {label} (`{layer_id}.geojson`)")
        lines.append("")
        lines.append(f"**{len(feats)} features.** Status counts: " +
                     ", ".join(f"`{k}` × {v}" for k, v in sorted(statuses.items(),
                                                                  key=lambda x: -x[1])))
        lines.append("")
        lines.append("| Name | State | Kind | Acres | Status |")
        lines.append("| --- | --- | --- | --- | --- |")
        for nm, st, kind, ac, status in sorted(rows, key=lambda r: (r[1], r[0])):
            ac_str = f"{int(ac):,}" if ac else ""
            lines.append(f"| {nm.title()} | {st} | {kind} | {ac_str} | {status} |")
        lines.append("")

    # Top-level summary
    lines.insert(5, "")
    lines.insert(5, "")
    lines.insert(5, "| Layer | Features | new | match-facility | match-legacy-overlay | fuzzy-facility |")
    lines.insert(6, "| --- | ---: | ---: | ---: | ---: | ---: |")
    for i, (lid, lbl, n, st, _) in enumerate(summary):
        lines.insert(7 + i,
                     f"| {lbl} | {n} | {st.get('new', 0)} "
                     f"| {st.get('match-facility', 0)} "
                     f"| {st.get('match-legacy-overlay/nps-coastal', 0) + st.get('match-legacy-overlay/nerr-reserves', 0) + st.get('match-legacy-overlay/nep-programs', 0) + st.get('match-legacy-overlay/marine-sanctuaries', 0) + st.get('match-legacy-overlay/marine-monuments', 0)} "
                     f"| {st.get('fuzzy-facility', 0)} |")

    OUT.write_text("\n".join(lines))
    print(f"[crossvalidate] wrote {OUT.relative_to(ROOT)}")
    for lid, lbl, n, st, sts in summary:
        print(f"  {lbl:55s} {n:4d} features  new={st.get('new',0):4d}  "
              f"existing-facility={st.get('match-facility',0):3d}  "
              f"states={len(sts)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
